spring:
  application:
    name: order-service
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/order_service?authSource=admin
server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka