spring:
  application:
    name: identity-service
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/identity_service?authSource=admin
server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka