server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://localhost:8081
          predicates:
            - Path=/products/**

        - id: order-service
          uri: http://localhost:8082
          predicates:
            - Path=/orders/**

        - id: customer-service
          uri: http://localhost:8083
          predicates:
            - Path=/customers/**

        - id: identity-service
          uri: http://localhost:8084
          predicates:
            - Path=/auth/**

        - id: payment-service
          uri: http://localhost:8086
          predicates:
            - Path=/payments/**

        - id: inventory-service
          uri: http://localhost:8087
          predicates:
            - Path=/inventories/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka