spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/product_service?authSource=admin

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka