spring:
  application:
    name: customer-service
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/customer_service?authSource=admin
server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka